'use client';

import { useState, useMemo } from 'react';
import { MATH_CONSTANTS, type MathConstant } from '@/lib/constants';

interface ConstantsTableProps {
  onSelectConstant?: (constantId: string) => void;
}

export default function ConstantsTable({ onSelectConstant }: ConstantsTableProps) {
  const [search, setSearch] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');

  const categories = [
    { id: 'all', label: 'All Constants' },
    { id: 'physics', label: 'Physics & Quantum ⚛️' },
    { id: 'fundamental', label: 'Fundamental' },
    { id: 'geometry', label: 'Geometry' },
    { id: 'analysis', label: 'Analysis' },
    { id: 'number-theory', label: 'Number Theory' },
    { id: 'algebra', label: 'Algebra' },
  ];

  const filteredConstants = useMemo(() => {
    return MATH_CONSTANTS.filter((c) => {
      const matchesSearch =
        c.name.toLowerCase().includes(search.toLowerCase()) ||
        c.symbol.toLowerCase().includes(search.toLowerCase()) ||
        c.description.toLowerCase().includes(search.toLowerCase()) ||
        c.digits.includes(search);
      const matchesCategory =
        selectedCategory === 'all' || c.category === selectedCategory;
      return matchesSearch && matchesCategory;
    });
  }, [search, selectedCategory]);

  return (
    <section id="constants-table" className="max-w-6xl mx-auto px-4 py-16">
      <div className="text-center mb-10">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary-500/10 border border-primary-500/20 text-primary-300 text-xs mb-3">
          📚 Mathematical Encyclopedia
        </div>
        <h2 className="text-3xl md:text-4xl font-bold mb-3">
          Explore Mathematical <span className="gradient-text">Constants</span>
        </h2>
        <p className="text-gray-400 text-sm max-w-2xl mx-auto">
          Every password generated by MathPass is grounded in real mathematical history. Browse our database of {MATH_CONSTANTS.length} famous constants and generate a custom password using any of them with a single click.
        </p>
      </div>

      {/* Filter and Search Bar */}
      <div className="glass-card rounded-2xl p-4 md:p-6 mb-6">
        <div className="flex flex-col md:flex-row gap-4 items-center justify-between">
          {/* Search Input */}
          <div className="relative w-full md:w-80">
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400">
              🔍
            </span>
            <input
              type="text"
              placeholder="Search constants (e.g. Pi, Euler, φ)..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-9 pr-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-primary-500"
            />
          </div>

          {/* Category Tabs */}
          <div className="flex flex-wrap gap-1.5 w-full md:w-auto">
            {categories.map((cat) => (
              <button
                key={cat.id}
                onClick={() => setSelectedCategory(cat.id)}
                className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                  selectedCategory === cat.id
                    ? 'bg-primary-600/30 text-white border border-primary-500/50'
                    : 'bg-white/5 text-gray-400 hover:text-white hover:bg-white/10 border border-white/5'
                }`}
              >
                {cat.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Table Container */}
      <div className="glass-card rounded-2xl overflow-hidden border border-white/10">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-sm">
            <thead>
              <tr className="border-b border-white/10 bg-white/5 text-xs text-gray-400 uppercase tracking-wider font-semibold">
                <th className="py-4 px-4">Symbol</th>
                <th className="py-4 px-4">Name</th>
                <th className="py-4 px-4">Decimal Expansion</th>
                <th className="py-4 px-4 hidden lg:table-cell">Meaning / Formula</th>
                <th className="py-4 px-4 hidden sm:table-cell">Discovered</th>
                <th className="py-4 px-4 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {filteredConstants.map((c) => (
                <tr
                  key={c.id}
                  className="hover:bg-white/5 transition-colors group"
                >
                  <td className="py-4 px-4 font-mono font-bold text-accent-400 text-base">
                    {c.symbol}
                  </td>
                  <td className="py-4 px-4 font-medium text-white">
                    <div>{c.name}</div>
                    <span className="text-[11px] text-gray-500 uppercase tracking-wide">
                      {c.category}
                    </span>
                  </td>
                  <td className="py-4 px-4 font-mono text-xs text-gray-300">
                    <span className="bg-black/30 px-2 py-1 rounded border border-white/5 inline-block">
                      {c.value.slice(0, 16)}...
                    </span>
                  </td>
                  <td className="py-4 px-4 text-xs text-gray-400 hidden lg:table-cell max-w-xs">
                    {c.description}
                  </td>
                  <td className="py-4 px-4 text-xs text-gray-400 hidden sm:table-cell">
                    {c.year}
                  </td>
                  <td className="py-4 px-4 text-right">
                    <button
                      onClick={() => {
                        if (onSelectConstant) {
                          onSelectConstant(c.id);
                        }
                        const generatorSection = document.getElementById('generator');
                        if (generatorSection) {
                          generatorSection.scrollIntoView({ behavior: 'smooth' });
                        }
                      }}
                      className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-primary-600/20 hover:bg-primary-600/40 text-primary-300 border border-primary-500/30 transition-all hover:scale-105"
                      title={`Generate password using ${c.name}`}
                    >
                      <span>⚡</span>
                      <span>Generate</span>
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {filteredConstants.length === 0 && (
          <div className="py-12 text-center text-gray-500 text-sm">
            No mathematical constants found matching &ldquo;{search}&rdquo;.
          </div>
        )}
      </div>
    </section>
  );
}
